# -*- coding: utf-8 -*-
"""practica 1 estadistica descrictiva

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UUSgNi-Z__znPs4yj72g0frDjdCDwwSK
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Cargar archivo CSV
df = pd.read_csv("Nacimientos.csv")

# Información básica
print("Información del dataset")
print(df.info())
print("Primeras filas del dataset")

print(df.head())
print("Resumen estadístico del dataset")
print(df.describe())

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Cargar archivo CSV y realizar el preprocesamiento necesario para asegurar que df esté definido
df = pd.read_csv("Nacimientos.csv")
columns_to_drop = ['INSPECCION CORREGIMIENTO O CASERIO NACIMIENTO', 'BARRIO', 'CENTRO POBLADO', 'DIRECCIÓN', 'NÚMERO HIJOS NACIDOS VIVOS', 'RURAL DISPERSO', 'ULTIMO AÑO APROBADO PADRE', 'NOMBRE ADMINISTRADORA', 'NIVEL EDUCATIVO MADRE', 'ULTIMO AÑO APROBADO MADRE', 'TIPO ADMINISTRADORA']
df = df.drop(columns=columns_to_drop, errors='ignore')

# Eliminar datos atípicos, como se hizo previamente
numerical_cols = ['PESO (Gramos)', 'TALLA (Centímetros)', 'TIEMPO DE GESTACIÓN', 'NÚMERO CONSULTAS PRENATALES', 'NÚMERO EMBARAZOS']

for col in numerical_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    df = df[(df[col] >= lower_bound) & (df[col] <= upper_bound)]

# Histograma y diagrama de caja para 'PESO (Gramos)'
plt.figure(figsize=(14, 6))

plt.subplot(1, 2, 1)
sns.histplot(df['PESO (Gramos)'], kde=True)
plt.title('Distribución de Peso (Gramos)')
plt.xlabel('Peso (Gramos)')
plt.ylabel('Frecuencia')

plt.subplot(1, 2, 2)
sns.boxplot(y=df['PESO (Gramos)'])
plt.title('Diagrama de Caja de Peso (Gramos)')
plt.ylabel('Peso (Gramos)')

plt.tight_layout()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Cargar archivo CSV y realizar el preprocesamiento necesario para asegurar que df esté definido
df = pd.read_csv("Nacimientos.csv")
columns_to_drop = ['INSPECCION CORREGIMIENTO O CASERIO NACIMIENTO', 'BARRIO', 'CENTRO POBLADO', 'DIRECCIÓN', 'NÚMERO HIJOS NACIDOS VIVOS', 'RURAL DISPERSO', 'ULTIMO AÑO APROBADO PADRE', 'NOMBRE ADMINISTRADORA', 'NIVEL EDUCATIVO MADRE', 'ULTIMO AÑO APROBADO MADRE', 'TIPO ADMINISTRADORA']
df = df.drop(columns=columns_to_drop, errors='ignore')

# Eliminar datos atípicos, como se hizo previamente
numerical_cols = ['PESO (Gramos)', 'TALLA (Centímetros)', 'TIEMPO DE GESTACIÓN', 'NÚMERO CONSULTAS PRENATALES', 'NÚMERO EMBARAZOS']

for col in numerical_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    df = df[(df[col] >= lower_bound) & (df[col] <= upper_bound)]

# Histograma y diagrama de caja para 'TALLA (Centímetros)'
plt.figure(figsize=(14, 6))

plt.subplot(1, 2, 1)
sns.histplot(df['TALLA (Centímetros)'], kde=True)
plt.title('Distribución de Talla (Centímetros)')
plt.xlabel('Talla (Centímetros)')
plt.ylabel('Frecuencia')

plt.subplot(1, 2, 2)
sns.boxplot(y=df['TALLA (Centímetros)'])
plt.title('Diagrama de Caja de Talla (Centímetros)')
plt.ylabel('Talla (Centímetros)')

plt.tight_layout()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Cargar archivo CSV y realizar el preprocesamiento necesario
df = pd.read_csv("Nacimientos.csv")
columns_to_drop = ['INSPECCION CORREGIMIENTO O CASERIO NACIMIENTO', 'BARRIO', 'CENTRO POBLADO', 'DIRECCIÓN', 'NÚMERO HIJOS NACIDOS VIVOS', 'RURAL DISPERSO', 'ULTIMO AÑO APROBADO PADRE', 'NOMBRE ADMINISTRADORA', 'NIVEL EDUCATIVO MADRE', 'ULTIMO AÑO APROBADO MADRE', 'TIPO ADMINISTRADORA']
df = df.drop(columns=columns_to_drop, errors='ignore')

# Eliminar datos atípicos, como se hizo previamente
numerical_cols = ['PESO (Gramos)', 'TALLA (Centímetros)', 'TIEMPO DE GESTACIÓN', 'NÚMERO CONSULTAS PRENATALES', 'NÚMERO EMBARAZOS']

for col in numerical_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    df = df[(df[col] >= lower_bound) & (df[col] <= upper_bound)]

# Histograma y diagrama de caja para 'PESO (Gramos)'
plt.figure(figsize=(14, 6))

plt.subplot(1, 2, 1)
sns.histplot(df['PESO (Gramos)'], kde=True)
plt.title('Distribución de Peso (Gramos)')
plt.xlabel('Peso (Gramos)')
plt.ylabel('Frecuencia')

plt.subplot(1, 2, 2)
sns.boxplot(y=df['PESO (Gramos)'])
plt.title('Diagrama de Caja de Peso (Gramos)')
plt.ylabel('Peso (Gramos)')

plt.tight_layout()
plt.show()

# Histograma y diagrama de caja para 'TALLA (Centímetros)'
plt.figure(figsize=(14, 6))

plt.subplot(1, 2, 1)
sns.histplot(df['TALLA (Centímetros)'], kde=True)
plt.title('Distribución de Talla (Centímetros)')
plt.xlabel('Talla (Centímetros)')
plt.ylabel('Frecuencia')

plt.subplot(1, 2, 2)
sns.boxplot(y=df['TALLA (Centímetros)'])
plt.title('Diagrama de Caja de Talla (Centímetros)')
plt.ylabel('Talla (Centímetros)')

plt.tight_layout()
plt.show()

"""### Observaciones de los gráficos:

**Para 'PESO (Gramos)':**
*   **Histograma:** Muestra una distribución aproximadamente normal, centrada alrededor de los 3200-3300 gramos. Parece haber una ligera asimetría hacia la izquierda (más nacimientos con pesos ligeramente menores a la media).
*   **Diagrama de Caja:** Confirma que la mayoría de los pesos se agrupan alrededor de la mediana, con una dispersión razonable. Los puntos fuera de los "bigotes" del diagrama de caja representan **valores atípicos (anomalías)**, indicando algunos nacimientos con pesos significativamente más bajos o más altos que la mayoría. Por ejemplo, se observan varios valores por debajo de los 2500 gramos, que podrían considerarse bajo peso al nacer.

**Para 'TALLA (Centímetros)':**
*   **Histograma:** La distribución de la talla también parece ser aproximadamente normal, concentrada alrededor de los 50 centímetros. La mayoría de los recién nacidos tienen tallas similares.
*   **Diagrama de Caja:** Similar al peso, la talla muestra una distribución compacta. Los valores atípicos en este gráfico indican nacimientos con tallas notablemente más pequeñas o más grandes. Se observan algunas tallas por debajo de los 46-47 centímetros y algunas por encima de los 53-54 centímetros, que son menos comunes en la muestra principal.
"""

df = df.dropna()
print("Información del dataset después de eliminar filas con valores faltantes:")
print(df.info())

# Valores faltantes
print("\nValores faltantes por columna:")
print(df.isnull().sum())

# Visualización de nulos
sns.heatmap(df.isnull(), cbar=False, cmap="viridis")
plt.title("Mapa de datos faltantes")
plt.show()

df = pd.read_csv("Nacimientos.csv")
columns_to_drop = ['INSPECCION CORREGIMIENTO O CASERIO NACIMIENTO', 'BARRIO', 'CENTRO POBLADO', 'DIRECCIÓN', 'NÚMERO HIJOS NACIDOS VIVOS', 'RURAL DISPERSO', 'ULTIMO AÑO APROBADO PADRE', 'NOMBRE ADMINISTRADORA', 'NIVEL EDUCATIVO MADRE', 'ULTIMO AÑO APROBADO MADRE', 'TIPO ADMINISTRADORA']
df = df.drop(columns=columns_to_drop, errors='ignore')
print("Información del dataset después de eliminar las columnas especificadas:")
print(df.info())



selected_columns = ['PESO (Gramos)', 'TALLA (Centímetros)', 'TIEMPO DE GESTACIÓN']
print(df[selected_columns].describe())

print(f"Shape of DataFrame before outlier removal: {df.shape}")

numerical_cols = ['PESO (Gramos)', 'TALLA (Centímetros)', 'TIEMPO DE GESTACIÓN', 'NÚMERO CONSULTAS PRENATALES', 'NÚMERO EMBARAZOS']

for col in numerical_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    df = df[(df[col] >= lower_bound) & (df[col] <= upper_bound)]

print(f"Shape of DataFrame after outlier removal: {df.shape}")

# Display basic information of the DataFrame after outlier removal
print("\nInformación del dataset después de eliminar datos atípicos:")
print(df.info())

import matplotlib.pyplot as plt
import seaborn as sns

# Histograma y diagrama de caja para 'PESO (Gramos)'
plt.figure(figsize=(14, 6))

plt.subplot(1, 2, 1)
sns.histplot(df['PESO (Gramos)'], kde=True)
plt.title('Distribución de Peso (Gramos)')
plt.xlabel('Peso (Gramos)')
plt.ylabel('Frecuencia')

plt.subplot(1, 2, 2)
sns.boxplot(y=df['PESO (Gramos)'])
plt.title('Diagrama de Caja de Peso (Gramos)')
plt.ylabel('Peso (Gramos)')

plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

# Histograma y diagrama de caja para 'TALLA (Centímetros)'
plt.figure(figsize=(14, 6))

plt.subplot(1, 2, 1)
sns.histplot(df['TALLA (Centímetros)'], kde=True)
plt.title('Distribución de Talla (Centímetros)')
plt.xlabel('Talla (Centímetros)')
plt.ylabel('Frecuencia')

plt.subplot(1, 2, 2)
sns.boxplot(y=df['TALLA (Centímetros)'])
plt.title('Diagrama de Caja de Talla (Centímetros)')
plt.ylabel('Talla (Centímetros)')

plt.tight_layout()
plt.show()

"""### Observaciones de los gráficos (después de la eliminación de datos atípicos):

**Para 'PESO (Gramos)':**
*   **Histograma:** La distribución sigue siendo aproximadamente normal, concentrada alrededor de la media. Al haber eliminado los valores atípicos extremos, la curva debería ser más simétrica y menos sesgada, mostrando una distribución más compacta de los pesos.
*   **Diagrama de Caja:** Después de la eliminación de valores atípicos, el diagrama de caja mostrará un rango más estrecho. Los "bigotes" representarán el rango de datos que no son atípicos. Cualquier punto que aún se muestre fuera de los bigotes en este gráfico, si los hay, serían valores atípicos residuales o casos muy extremos que aún permanecen dentro de los criterios de 1.5 * IQR pero que son dignos de mención.

**Para 'TALLA (Centímetros)':**
*   **Histograma:** La distribución de la talla también debe aparecer más centrada y con menos dispersión en los extremos, debido a la remoción de valores atípicos. La mayoría de los recién nacidos tendrán tallas cercanas al promedio.
*   **Diagrama de Caja:** Similar al peso, la eliminación de valores atípicos resultará en un diagrama de caja más compacto. Los rangos intercuartílicos y los bigotes deberían reflejar una mayor homogeneidad en las tallas. Los valores que se muestran como atípicos en este nuevo gráfico (si existen) serían los casos más alejados dentro de la distribución que aún cumplen los criterios de filtrado aplicados.
"""

import matplotlib.pyplot as plt
import seaborn as sns

# Histograma y diagrama de caja para 'PESO (Gramos)'
plt.figure(figsize=(14, 6))

plt.subplot(1, 2, 1)
sns.histplot(df['PESO (Gramos)'], kde=True)
plt.title('Distribución de Peso (Gramos)')
plt.xlabel('Peso (Gramos)')
plt.ylabel('Frecuencia')

plt.subplot(1, 2, 2)
sns.boxplot(y=df['PESO (Gramos)'])
plt.title('Diagrama de Caja de Peso (Gramos)')
plt.ylabel('Peso (Gramos)')

plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

# Histograma y diagrama de caja para 'TALLA (Centímetros)'
plt.figure(figsize=(14, 6))

plt.subplot(1, 2, 1)
sns.histplot(df['TALLA (Centímetros)'], kde=True)
plt.title('Distribución de Talla (Centímetros)')
plt.xlabel('Talla (Centímetros)')
plt.ylabel('Frecuencia')

plt.subplot(1, 2, 2)
sns.boxplot(y=df['TALLA (Centímetros)'])
plt.title('Diagrama de Caja de Talla (Centímetros)')
plt.ylabel('Talla (Centímetros)')

plt.tight_layout()
plt.show()

import pandas as pd

# Load the dataset again to ensure a fresh start for filtering demonstration
df = pd.read_csv("Nacimientos.csv")

# Define columns to drop, as identified in previous steps
columns_to_drop = ['INSPECCION CORREGIMIENTO O CASERIO NACIMIENTO', 'BARRIO', 'CENTRO POBLADO', 'DIRECCIÓN', 'NÚMERO HIJOS NACIDOS VIVOS', 'RURAL DISPERSO', 'ULTIMO AÑO APROBADO PADRE', 'NOMBRE ADMINISTRADORA', 'NIVEL EDUCATIVO MADRE', 'ULTIMO AÑO APROBADO MADRE', 'TIPO ADMINISTRADORA']
df = df.drop(columns=columns_to_drop, errors='ignore')

print(f"Shape of DataFrame before outlier removal: {df.shape}")

# Define numerical columns for outlier removal
numerical_cols = ['PESO (Gramos)', 'TALLA (Centímetros)', 'TIEMPO DE GESTACIÓN', 'NÚMERO CONSULTAS PRENATALES', 'NÚMERO EMBARAZOS']

# Apply IQR-based outlier filtering
for col in numerical_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    df = df[(df[col] >= lower_bound) & (df[col] <= upper_bound)]

print(f"Shape of DataFrame after outlier removal: {df.shape}")

print("\nInformación del dataset después de eliminar datos atípicos:")
print(df.info())

import matplotlib.pyplot as plt
import seaborn as sns

# Histograma y diagrama de caja para 'PESO (Gramos)' después de la eliminación de outliers
plt.figure(figsize=(14, 6))

plt.subplot(1, 2, 1)
sns.histplot(df['PESO (Gramos)'], kde=True)
plt.title('Distribución de Peso (Gramos) después de Outliers')
plt.xlabel('Peso (Gramos)')
plt.ylabel('Frecuencia')

plt.subplot(1, 2, 2)
sns.boxplot(y=df['PESO (Gramos)'])
plt.title('Diagrama de Caja de Peso (Gramos) después de Outliers')
plt.ylabel('Peso (Gramos)')

plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

# Histograma y diagrama de caja para 'TALLA (Centímetros)' después de la eliminación de outliers
plt.figure(figsize=(14, 6))

plt.subplot(1, 2, 1)
sns.histplot(df['TALLA (Centímetros)'], kde=True)
plt.title('Distribución de Talla (Centímetros) después de Outliers')
plt.xlabel('Talla (Centímetros)')
plt.ylabel('Frecuencia')

plt.subplot(1, 2, 2)
sns.boxplot(y=df['TALLA (Centímetros)'])
plt.title('Diagrama de Caja de Talla (Centímetros) después de Outliers')
plt.ylabel('Talla (Centímetros)')

plt.tight_layout()
plt.show()

"""### Observaciones de los gráficos (después de la eliminación de datos atípicos):

**Para 'PESO (Gramos)':**
*   **Histograma:** La distribución sigue siendo aproximadamente normal, concentrada alrededor de la media. Al haber eliminado los valores atípicos extremos, la curva debería ser más simétrica y menos sesgada, mostrando una distribución más compacta de los pesos.
*   **Diagrama de Caja:** Después de la eliminación de valores atípicos, el diagrama de caja mostrará un rango más estrecho. Los "bigotes" representarán el rango de datos que no son atípicos. Cualquier punto que aún se muestre fuera de los bigotes en este gráfico, si los hay, serían valores atípicos residuales o casos muy extremos que aún permanecen dentro de los criterios de 1.5 * IQR pero que son dignos de mención.

**Para 'TALLA (Centímetros)':**
*   **Histograma:** La distribución de la talla también debe aparecer más centrada y con menos dispersión en los extremos, debido a la remoción de valores atípicos. La mayoría de los recién nacidos tendrán tallas cercanas al promedio.
*   **Diagrama de Caja:** Similar al peso, la eliminación de valores atípicos resultará en un diagrama de caja más compacto. Los rangos intercuartílicos y los bigotes deberían reflejar una mayor homogeneidad en las tallas. Los valores que se muestran como atípicos en este nuevo gráfico (si existen) serían los casos más alejados dentro de la distribución que aún cumplen los criterios de filtrado aplicados.

### Observaciones de los gráficos (después de la eliminación de datos atípicos):

**Para 'PESO (Gramos)':**
*   **Histograma:** La distribución sigue siendo aproximadamente normal, concentrada alrededor de la media. Al haber eliminado los valores atípicos extremos, la curva debería ser más simétrica y menos sesgada, mostrando una distribución más compacta de los pesos.
*   **Diagrama de Caja:** Después de la eliminación de valores atípicos, el diagrama de caja mostrará un rango más estrecho. Los "bigotes" representarán el rango de datos que no son atípicos. Cualquier punto que aún se muestre fuera de los bigotes en este gráfico, si los hay, serían valores atípicos residuales o casos muy extremos que aún permanecen dentro de los criterios de 1.5 * IQR pero que son dignos de mención.

**Para 'TALLA (Centímetros)':**
*   **Histograma:** La distribución de la talla también debe aparecer más centrada y con menos dispersión en los extremos, debido a la remoción de valores atípicos. La mayoría de los recién nacidos tendrán tallas cercanas al promedio.
*   **Diagrama de Caja:** Similar al peso, la eliminación de valores atípicos resultará en un diagrama de caja más compacto. Los rangos intercuartílicos y los bigotes deberían reflejar una mayor homogeneidad en las tallas. Los valores que se muestran como atípicos en este nuevo gráfico (si existen) serían los casos más alejados dentro de la distribución que aún cumplen los criterios de filtrado aplicados.
"""



"""# Task
To present a comprehensive overview of the dataset's categorical features, create two pie charts: one illustrating the distribution of 'SEXO' (Gender) and another showing the distribution of 'FORMA DE PARTO' (Type of Delivery). Accompany these visualizations with a description of the observed proportions in each category, based on the "Nacimientos.csv" dataset.

## Generar Diagrama de Torta para Sexo

### Subtask:
Calcular las frecuencias de la variable 'SEXO' y crear un diagrama de torta para visualizar la proporción de cada categoría (Masculino/Femenino).

**Reasoning**:
To calculate the frequencies and generate a pie chart, I will use `value_counts()` on the 'SEXO' column and then `plot.pie()` to visualize the distribution with percentages.
"""

import matplotlib.pyplot as plt

# Calculate frequencies of 'SEXO'
sex_counts = df['SEXO'].value_counts()

# Create a pie chart
plt.figure(figsize=(8, 8))
sex_counts.plot.pie(autopct='%1.1f%%', startangle=90, colors=['skyblue', 'lightcoral'])
plt.title('Distribución de Sexo')
plt.ylabel('') # Hide the default 'SEXO' label on the y-axis for better aesthetics
plt.show()

"""# Task
## Realizar Test de Shapiro-Wilk para Peso y Talla

### Subtask:
Aplicar el test de Shapiro-Wilk a las variables 'PESO (Gramos)' y 'TALLA (Centímetros)' para evaluar su normalidad. Este test es adecuado para muestras pequeñas a moderadas y devuelve un estadístico y un valor p.

### Reasoning:
Utilizaré la función `shapiro` del módulo `scipy.stats` para realizar el test de normalidad. Esta función es apropiada para verificar si los datos se distribuyen normalmente, proporcionando un estadístico y un valor p que nos ayudarán a tomar una decisión sobre la normalidad de las variables. Un valor p bajo (típicamente < 0.05) indicará que la hipótesis nula de normalidad se rechaza.

## Realizar Test de Shapiro-Wilk para Peso y Talla

### Subtask:
Aplicar el test de Shapiro-Wilk a las variables 'PESO (Gramos)' y 'TALLA (Centímetros)' para evaluar su normalidad. Este test es adecuado para muestras pequeñas a moderadas y devuelve un estadístico y un valor p.

**Reasoning**:
To perform the Shapiro-Wilk test, I need to import the `shapiro` function from the `scipy.stats` module and then apply it to the specified columns, printing the statistic and p-value for each.
"""

from scipy.stats import shapiro

# Apply Shapiro-Wilk test to 'PESO (Gramos)'
shapiro_peso_stat, shapiro_peso_p = shapiro(df['PESO (Gramos)'])
print(f"Shapiro-Wilk Test for PESO (Gramos):\n Statistic={shapiro_peso_stat:.3f}, p-value={shapiro_peso_p:.3f}")

# Apply Shapiro-Wilk test to 'TALLA (Centímetros)'
shapiro_talla_stat, shapiro_talla_p = shapiro(df['TALLA (Centímetros)'])
print(f"Shapiro-Wilk Test for TALLA (Centímetros):\n Statistic={shapiro_talla_stat:.3f}, p-value={shapiro_talla_p:.3f}")

"""## Realizar Test de Kolmogorov-Smirnov para Peso y Talla

### Subtask:
Aplicar el test de Kolmogorov-Smirnov a las variables 'PESO (Gramos)' y 'TALLA (Centímetros)' para evaluar su normalidad. Este test compara la distribución observada con una distribución teórica (normal) y devuelve un estadístico D y un valor p.

**Reasoning**:
To perform the Kolmogorov-Smirnov test for normality, I will first standardize the 'PESO (Gramos)' column by subtracting its mean and dividing by its standard deviation. Then, I will apply the `kstest` function from `scipy.stats` to compare the standardized data against a standard normal distribution.
"""

from scipy.stats import kstest
from scipy.stats import norm

# Standardize 'PESO (Gramos)' for the Kolmogorov-Smirnov test
mean_peso = df['PESO (Gramos)'].mean()
std_peso = df['PESO (Gramos)'].std()
standardized_peso = (df['PESO (Gramos)'] - mean_peso) / std_peso

# Apply Kolmogorov-Smirnov test to 'PESO (Gramos)'
ks_peso_stat, ks_peso_p = kstest(standardized_peso, 'norm')
print(f"Kolmogorov-Smirnov Test for PESO (Gramos):\n Statistic={ks_peso_stat:.3f}, p-value={ks_peso_p:.3f}")

"""**Reasoning**:
To complete the subtask, I will now apply the Kolmogorov-Smirnov test to the 'TALLA (Centímetros)' column. This involves standardizing the column first, then using `kstest` to compare it against a normal distribution, and finally printing the results.


"""

from scipy.stats import kstest
from scipy.stats import norm

# Standardize 'TALLA (Centímetros)' for the Kolmogorov-Smirnov test
mean_talla = df['TALLA (Centímetros)'].mean()
std_talla = df['TALLA (Centímetros)'].std()
standardized_talla = (df['TALLA (Centímetros)'] - mean_talla) / std_talla

# Apply Kolmogorov-Smirnov test to 'TALLA (Centímetros)'
ks_talla_stat, ks_talla_p = kstest(standardized_talla, 'norm')
print(f"Kolmogorov-Smirnov Test for TALLA (Centímetros):\n Statistic={ks_talla_stat:.3f}, p-value={ks_talla_p:.3f}")

"""## Realizar Test de Anderson-Darling para Peso y Talla

### Subtask:
Aplicar el test de Anderson-Darling a las variables 'PESO (Gramos)' y 'TALLA (Centímetros)' para evaluar su normalidad. Este test es una modificación del Kolmogorov-Smirnov que da más peso a las colas de la distribución, y devuelve un estadístico y sus valores críticos.

**Reasoning**:
To perform the Anderson-Darling test, I will import the `anderson` function from `scipy.stats` and apply it to the 'PESO (Gramos)' column, then print the statistic and critical values.
"""

from scipy.stats import anderson

# Apply Anderson-Darling test to 'PESO (Gramos)'
result_peso = anderson(df['PESO (Gramos)'], dist='norm')
print(f"Anderson-Darling Test for PESO (Gramos):\n Statistic={result_peso.statistic:.3f}\n Critical Values={result_peso.critical_values}\n Significance Levels={result_peso.significance_level}")

"""**Reasoning**:
To complete the subtask, I will now apply the Anderson-Darling test to the 'TALLA (Centímetros)' column, and print the resulting statistic and critical values.


"""

from scipy.stats import anderson

# Apply Anderson-Darling test to 'TALLA (Centímetros)'
result_talla = anderson(df['TALLA (Centímetros)'], dist='norm')
print(f"Anderson-Darling Test for TALLA (Centímetros):\n Statistic={result_talla.statistic:.3f}\n Critical Values={result_talla.critical_values}\n Significance Levels={result_talla.significance_level}")

"""## Generar Gráficos QQ-plot para Peso y Talla

### Subtask:
Crear gráficos QQ-plot (quantile-quantile plot) para 'PESO (Gramos)' y 'TALLA (Centímetros)'. Estos gráficos son herramientas visuales para evaluar si un conjunto de datos se ajusta a una distribución normal, comparando sus cuantiles con los de una distribución normal teórica.

**Reasoning**:
To create QQ-plots for 'PESO (Gramos)' and 'TALLA (Centímetros)' to visually assess their normality, I will import the necessary `qqplot` function from `statsmodels.api` and `matplotlib.pyplot`, then generate and display two separate plots with appropriate titles and a standardized line for comparison.
"""

from statsmodels.graphics.gofplots import qqplot
import matplotlib.pyplot as plt

# QQ-plot para 'PESO (Gramos)'
plt.figure(figsize=(8, 6))
qqplot(df['PESO (Gramos)'], line='s')
plt.title('QQ-plot para Peso (Gramos)')
plt.show()

# QQ-plot para 'TALLA (Centímetros)'
plt.figure(figsize=(8, 6))
qqplot(df['TALLA (Centímetros)'], line='s')
plt.title('QQ-plot para Talla (Centímetros)')
plt.show()

"""## Presentar Conclusiones de Normalidad

### Subtask:
Analizar los resultados de los tests de Shapiro-Wilk, Kolmogorov-Smirnov y Anderson-Darling, junto con la inspección visual de los gráficos QQ-plot, para determinar si las variables 'PESO (Gramos)' y 'TALLA (Centímetros)' siguen una distribución normal después de la eliminación de outliers, y resumir las conclusiones de este análisis.

### Conclusiones del Análisis de Normalidad para 'PESO (Gramos)' y 'TALLA (Centímetros)'

Después de eliminar los datos atípicos y aplicar los tests de normalidad (Shapiro-Wilk, Kolmogorov-Smirnov, Anderson-Darling) y la inspección visual mediante QQ-plots, se presentan las siguientes conclusiones:

#### Para 'PESO (Gramos)':

*   **Test de Shapiro-Wilk**: `Statistic=0.997`, `p-value=0.010`. Con un nivel de significancia de 0.05, el p-value (0.010) es menor que 0.05, lo que sugiere que la hipótesis nula de normalidad se rechaza. Sin embargo, el valor p está cerca del umbral, lo que indica que la desviación de la normalidad podría ser leve.

*   **Test de Kolmogorov-Smirnov**: `Statistic=0.019`, `p-value=0.704`. Con un nivel de significancia de 0.05, el p-value (0.704) es mayor que 0.05. Esto significa que no hay suficiente evidencia para rechazar la hipótesis nula de normalidad. Este test sugiere que 'PESO (Gramos)' sigue una distribución normal.

*   **Test de Anderson-Darling**: `Statistic=0.598`. Los valores críticos son `[0.574, 0.654, 0.785, 0.915, 1.089]` para niveles de significancia `[15.0, 10.0, 5.0, 2.5, 1.0]` respectivamente. El estadístico (0.598) es mayor que el valor crítico para el 15% (0.574) y 10% (0.654) pero menor que el valor crítico para el 5% (0.785) de significancia. Esto indica que a un 5% de significancia, no se rechaza la normalidad. Sin embargo, si se usa un nivel de significancia más relajado (15% o 10%), se podría rechazar la normalidad.

*   **QQ-plot**: El QQ-plot para 'PESO (Gramos)' muestra que la mayoría de los puntos se alinean bastante bien con la línea de referencia central, especialmente en la parte media de la distribución. Hay ligeras desviaciones en las colas, pero en general, la forma sugiere una aproximación razonable a la normalidad.

**Conclusión para 'PESO (Gramos)'**: Los resultados de los tests son mixtos. El test de Shapiro-Wilk sugiere una desviación, mientras que el Kolmogorov-Smirnov no la encuentra. El Anderson-Darling es sensible a las colas y muestra una posible desviación a niveles de significancia más altos. Sin embargo, visualmente, el QQ-plot y el histograma (generado previamente) indican una distribución que se acerca bastante a la normal. Para fines prácticos en muchos análisis, 'PESO (Gramos)' podría ser tratado como aproximadamente normal, especialmente considerando la eliminación de outliers.

#### Para 'TALLA (Centímetros)':

*   **Test de Shapiro-Wilk**: `Statistic=0.968`, `p-value=0.000`. Con un p-value extremadamente bajo (cercano a 0), la hipótesis nula de normalidad se rechaza contundentemente. Esto indica que 'TALLA (Centímetros)' no sigue una distribución normal.

*   **Test de Kolmogorov-Smirnov**: `Statistic=0.119`, `p-value=0.000`. Similar al Shapiro-Wilk, el p-value es cercano a 0, lo que lleva a un claro rechazo de la hipótesis nula de normalidad. Este test también indica que 'TALLA (Centímetros)' no es normal.

*   **Test de Anderson-Darling**: `Statistic=18.713`. Este estadístico es significativamente mayor que todos los valores críticos (`[0.574, 0.654, 0.785, 0.915, 1.089]`) en todos los niveles de significancia. Esto resulta en un claro rechazo de la normalidad para 'TALLA (Centímetros)'.

*   **QQ-plot**: El QQ-plot para 'TALLA (Centímetros)' muestra una desviación considerable de la línea de referencia, especialmente en las colas. Los puntos se curvan lejos de la línea, confirmando visualmente la falta de normalidad.

**Conclusión para 'TALLA (Centímetros)'**: Todos los tests estadísticos (Shapiro-Wilk, Kolmogorov-Smirnov, Anderson-Darling) y el QQ-plot indican consistentemente que la variable 'TALLA (Centímetros)' **no sigue una distribución normal**.

## Final Task

### Subtask:
Proporcionar un resumen completo del análisis de normalidad realizado, incluyendo los resultados clave de cada test y las interpretaciones de los QQ-plots, para las variables 'PESO (Gramos)' y 'TALLA (Centímetros)'.

## Summary:

### Data Analysis Key Findings

*   **For 'PESO (Gramos)':**
    *   **Shapiro-Wilk Test:** A statistic of 0.997 and a p-value of 0.010 led to the rejection of the null hypothesis of normality at the 0.05 significance level, suggesting a deviation.
    *   **Kolmogorov-Smirnov Test:** A statistic of 0.019 and a p-value of 0.704 indicated that the null hypothesis of normality could not be rejected, suggesting a normal distribution.
    *   **Anderson-Darling Test:** A statistic of 0.598, which was greater than the critical value for 15% significance (0.574) but less than the critical value for 10% significance (0.654), suggested rejection of normality at 15% but not at 10% or 5% significance levels.
    *   **QQ-plot:** Visually, most points aligned well with the reference line, especially in the middle, indicating a reasonable approximation to normality despite slight deviations in the tails.
    *   **Overall Conclusion for 'PESO (Gramos)'**: The tests provided mixed results, with Shapiro-Wilk suggesting deviation and Kolmogorov-Smirnov failing to reject normality. However, the visual evidence from the QQ-plot and the Anderson-Darling test at common significance levels (like 5%) indicate that 'PESO (Gramos)' can be considered approximately normally distributed for practical purposes after outlier removal.

*   **For 'TALLA (Centímetros)':**
    *   **Shapiro-Wilk Test:** A statistic of 0.968 and a p-value of 0.000 strongly rejected the null hypothesis of normality.
    *   **Kolmogorov-Smirnov Test:** A statistic of 0.119 and a p-value of 0.000 also strongly rejected the null hypothesis of normality.
    *   **Anderson-Darling Test:** A statistic of 18.713, which was significantly higher than all critical values across all tested significance levels (15% to 1%), definitively rejected the null hypothesis of normality.
    *   **QQ-plot:** The plot showed considerable deviation from the reference line, particularly in the tails, confirming the non-normal distribution.
    *   **Overall Conclusion for 'TALLA (Centímetros)'**: All statistical tests and visual inspection consistently indicated that 'TALLA (Centímetros)' **does not** follow a normal distribution.

### Insights or Next Steps

*   'PESO (Gramos)' can likely be treated as approximately normally distributed for further parametric analyses, despite minor deviations detected by some tests.
*   For 'TALLA (Centímetros)', given its clear non-normal distribution, future analyses involving this variable should consider non-parametric statistical methods or transformations to achieve normality if parametric tests are desired.
"""